package com.funti.hello.spring.boot.mybatis.dao;

import com.funti.hello.spring.boot.mybatis.entity.Appuser;
import java.util.List;

public interface AppuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appuser
     *
     * @mbg.generated Fri Mar 01 15:52:33 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appuser
     *
     * @mbg.generated Fri Mar 01 15:52:33 CST 2019
     */
    int insert(Appuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appuser
     *
     * @mbg.generated Fri Mar 01 15:52:33 CST 2019
     */
    Appuser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appuser
     *
     * @mbg.generated Fri Mar 01 15:52:33 CST 2019
     */
    List<Appuser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appuser
     *
     * @mbg.generated Fri Mar 01 15:52:33 CST 2019
     */
    int updateByPrimaryKey(Appuser record);
}