package com.funti.hello.spring.boot.mybatis.entity;

import java.io.Serializable;

public class Appuser implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appuser.id
     *
     * @mbg.generated Fri Mar 01 15:52:33 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appuser.login_name
     *
     * @mbg.generated Fri Mar 01 15:52:33 CST 2019
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appuser.user_name
     *
     * @mbg.generated Fri Mar 01 15:52:33 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appuser.password
     *
     * @mbg.generated Fri Mar 01 15:52:33 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appuser.age
     *
     * @mbg.generated Fri Mar 01 15:52:33 CST 2019
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appuser.id
     *
     * @return the value of appuser.id
     *
     * @mbg.generated Fri Mar 01 15:52:33 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appuser.id
     *
     * @param id the value for appuser.id
     *
     * @mbg.generated Fri Mar 01 15:52:33 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appuser.login_name
     *
     * @return the value of appuser.login_name
     *
     * @mbg.generated Fri Mar 01 15:52:33 CST 2019
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appuser.login_name
     *
     * @param loginName the value for appuser.login_name
     *
     * @mbg.generated Fri Mar 01 15:52:33 CST 2019
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appuser.user_name
     *
     * @return the value of appuser.user_name
     *
     * @mbg.generated Fri Mar 01 15:52:33 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appuser.user_name
     *
     * @param userName the value for appuser.user_name
     *
     * @mbg.generated Fri Mar 01 15:52:33 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appuser.password
     *
     * @return the value of appuser.password
     *
     * @mbg.generated Fri Mar 01 15:52:33 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appuser.password
     *
     * @param password the value for appuser.password
     *
     * @mbg.generated Fri Mar 01 15:52:33 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appuser.age
     *
     * @return the value of appuser.age
     *
     * @mbg.generated Fri Mar 01 15:52:33 CST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appuser.age
     *
     * @param age the value for appuser.age
     *
     * @mbg.generated Fri Mar 01 15:52:33 CST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}