package com.funti.hello.spring.boot.mybatis.entity;

public class Paper {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.paper_id
     *
     * @mbg.generated Fri Mar 01 15:52:33 CST 2019
     */
    private Long paperId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.name
     *
     * @mbg.generated Fri Mar 01 15:52:33 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.number
     *
     * @mbg.generated Fri Mar 01 15:52:33 CST 2019
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.detail
     *
     * @mbg.generated Fri Mar 01 15:52:33 CST 2019
     */
    private String detail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.paper_id
     *
     * @return the value of paper.paper_id
     *
     * @mbg.generated Fri Mar 01 15:52:33 CST 2019
     */
    public Long getPaperId() {
        return paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.paper_id
     *
     * @param paperId the value for paper.paper_id
     *
     * @mbg.generated Fri Mar 01 15:52:33 CST 2019
     */
    public void setPaperId(Long paperId) {
        this.paperId = paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.name
     *
     * @return the value of paper.name
     *
     * @mbg.generated Fri Mar 01 15:52:33 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.name
     *
     * @param name the value for paper.name
     *
     * @mbg.generated Fri Mar 01 15:52:33 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.number
     *
     * @return the value of paper.number
     *
     * @mbg.generated Fri Mar 01 15:52:33 CST 2019
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.number
     *
     * @param number the value for paper.number
     *
     * @mbg.generated Fri Mar 01 15:52:33 CST 2019
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.detail
     *
     * @return the value of paper.detail
     *
     * @mbg.generated Fri Mar 01 15:52:33 CST 2019
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.detail
     *
     * @param detail the value for paper.detail
     *
     * @mbg.generated Fri Mar 01 15:52:33 CST 2019
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }
}